network:
  arch: resnet
  ckpt_path: logs
  trained_model_path: pretrained/resnet/pretrained_resnet_e50.pth
hparams:
  batch_size: 8
  epoch_num: 50
  initial_lr: 1e-2
  ultimate_lr: 1e-5
  weight_decay: 5e-4
data: 
  name: got10k
  root_dir: data/got10k