network:
  arch: alexnet
  pretrained: pretrained/siamfc_alexnet_e50.pth
  trained_model_path: pretrained/alexnet/pretrained_alexnet_e50.pth
hparams:
  batch_size: 8
  epoch_num: 50
  initial_lr: 1e-2
  ultimate_lr: 1e-5
  weight_decay: 5e-4
data:
  name: got10k
  root_dir: data/GOT-10k