# Default configurations
model:
  encoder: alexnet
  weights: None
  input_size: (17, 17)
  output_size: (272, 272)
data:
  dataset: ImageNet2015
  dir: ./data/ILSVRC
  exemplar_size: (127, 127)
  target_size: (255, 255)
hparams:
  max_epochs: 50
  batch_size: 8
  learning_rate: (1e-2, 1e-5)