# Default configurations
model:
  architecture: alexnet
  weights: ???
  input_size: (17, 17)
  output_size: (272, 272)
data:
  dataset: ImageNet
  dir: ./data/ILSVRC
  train: ???
  test: ???
  target_size: (127, 127)
  search_size: (255, 255)
hparams:
  batch_size: 8
  max_epochs: 50
  lr: (1e-2, 1e-5)
