network:
  arch: alexnet-torch
  pretrained: pretrained/alexnet/siamfc_alexnet_e50.pth
hparams:
  batch_size: 8
  epoch_num: 50
  initial_lr: 1e-2
  ultimate_lr: 1e-5
data_dir: data/GOT-10k/test/GOT-10k_Test_000100/
tracker:
  exemplar_sz: 127
  instance_sz: 255
  score_sz: 17
  upsample_factor: 16
  context: 0.5
  scale_num: 5 #3
  scale_step: 1.025
  scale_lr: 0.35
  scale_penalty: 0.975
  window_influence: 0.176