network:
  arch: alexnet
  pretrained: pretrained/alexnet/siamfc_alexnet_e50.pth
hparams:
  batch_size: 8
  epoch_num: 50
  initial_lr: 1e-2
  ultimate_lr: 1e-5
data_dir: data/GOT-10k/test/GOT-10k_Test_000150/
# data_dir = 'C:/Users/xw/Desktop/tracking restart/siamfc-pytorch/data/GOT-10k/train/GOT-10k_Train_000001/'
tracker:
  exemplar_sz: 127
  instance_sz: 255
  score_sz: 17
  upsample_factor: 16
  context: 0.5
  scale_num: 9 #3
  scale_step: 1.025
  scale_lr: 0.35
  scale_penalty: 0.975
  window_influence: 0.176